// WebCurveEditor.cpp — JUCE 8 WebBrowserComponent-based plugin editor.
//
// The HTML/JS bundle (dist/index.html + dist/bundle.js) is compiled into
// BinaryData by CMake's juce_add_binary_data(DrawnCurveWebUI …).
// The resource provider serves those byte arrays to WKWebView without a server.

#include "WebCurveEditor.h"
#include <BinaryDataWebUI.h>      // generated by juce_add_binary_data(DrawnCurveWebUI …)

// ── Helpers ───────────────────────────────────────────────────────────────────

// Build a var::Object (JSON object) from key-value pairs for event payloads.
static juce::var makeObj (std::initializer_list<std::pair<juce::String, juce::var>> pairs)
{
    auto obj = std::make_unique<juce::DynamicObject>();
    for (auto& [k, v] : pairs)
        obj->setProperty (k, v);
    return juce::var (obj.release());
}

// ── Resource provider ─────────────────────────────────────────────────────────
// Serves index.html and bundle.js from the BinaryData arrays generated by CMake.

std::optional<juce::WebBrowserComponent::Resource>
WebCurveEditor::provideResource (const juce::String& path)
{
    struct Entry { const char* data; int size; juce::String mime; };

    static const std::array<std::pair<const char*, Entry>, 3> table {{
        { "/",           { BinaryData::index_html,
                           BinaryData::index_htmlSize,
                           "text/html; charset=utf-8" } },
        { "/index.html", { BinaryData::index_html,
                           BinaryData::index_htmlSize,
                           "text/html; charset=utf-8" } },
        { "/bundle.js",  { BinaryData::bundle_js,
                           BinaryData::bundle_jsSize,
                           "application/javascript" } },
    }};

    for (auto& [key, entry] : table)
    {
        if (path == key)
        {
            std::vector<std::byte> bytes (static_cast<std::size_t> (entry.size));
            std::memcpy (bytes.data(), entry.data, static_cast<std::size_t> (entry.size));
            return juce::WebBrowserComponent::Resource { std::move (bytes), entry.mime };
        }
    }
    return std::nullopt;
}

// ── Options builder ───────────────────────────────────────────────────────────

juce::WebBrowserComponent::Options WebCurveEditor::buildOptions (WebCurveEditor* owner)
{
    using juce::WebBrowserComponent;
    using juce::var;
    using juce::Array;

    return WebBrowserComponent::Options{}
        .withResourceProvider ([](const juce::String& path)
            { return WebCurveEditor::provideResource (path); },
            WebBrowserComponent::getResourceProviderRoot())
        .withNativeIntegrationEnabled()

        // ── JS → C++: UI signals ──────────────────────────────────────────────
        // "log" — diagnostic console.log mirror from JS
        .withEventListener ("log", [] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const auto level = args[0]["level"].toString();
            const auto msg   = args[0]["msg"].toString();
            std::fprintf (stderr, "[js:%s] %s\n",
                          level.toRawUTF8(), msg.toRawUTF8());
            std::fflush (stderr);
        })

        // "uiReady" — page has loaded and wants the initial state snapshot
        .withEventListener ("uiReady", [owner] (const Array<var>&)
        {
            owner->pageReady = true;
            juce::MessageManager::callAsync ([owner]
            {
                owner->sendStateSnapshot();
                // Start the engine playing.  Without this, a fresh plugin
                // instance has _isPlaying=false → processLane returns early
                // → no MIDI output, no quantization, despite a valid
                // snapshot being in place.  The user can still toggle via
                // the transport; this is just a sane default for the
                // standalone & for hosts that don't drive the param.
                owner->proc.setPlaying (true);
            });
        })

        // "setParam" — { id: "l0_ccNumber", value: 0..1 (host-normalised) }
        // Use this when the JS side already pre-normalises (LANE_MAP + GLOBAL_PARAM_MAP).
        .withEventListener ("setParam", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const auto& obj = args[0];
            const auto id    = obj["id"].toString();
            const float val  = static_cast<float> (static_cast<double> (obj["value"]));
            if (auto* p = owner->proc.apvts.getParameter (id))
                p->setValueNotifyingHost (val);
        })

        // "setParamActual" — { id, value: actual-domain value }
        // The C++ side does the 0..1 conversion through the parameter's own
        // NormalisableRange — so JS doesn't need to know about skew factors
        // (e.g. playbackSpeed has skew=0.5 — a log curve we don't want to
        // duplicate on the JS side).
        .withEventListener ("setParamActual", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const auto& obj = args[0];
            const auto  id  = obj["id"].toString();
            const float val = static_cast<float> (static_cast<double> (obj["value"]));
            if (auto* p = dynamic_cast<juce::RangedAudioParameter*> (
                              owner->proc.apvts.getParameter (id)))
                p->setValueNotifyingHost (p->convertTo0to1 (val));
        })

        // "setCurve" — { lane: 0, data: [0.0, …, 1.0] (256 floats or null) }
        .withEventListener ("setCurve", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const auto& obj = args[0];
            const int lane  = static_cast<int> (obj["lane"]);
            const auto& arr = *obj["data"].getArray();

            if (arr.isEmpty())
            {
                owner->proc.clearSnapshot (lane);
            }
            else
            {
                auto snap = std::make_unique<float[]> (256);
                for (int i = 0; i < 256; ++i)
                    snap[static_cast<std::size_t> (i)] = static_cast<float> (static_cast<double> (arr[i]));
                owner->proc.setSnapshotFromArray (lane, snap.get(), 256);
            }
        })

        // "setFocus" — { lane: N }
        .withEventListener ("setFocus", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            // No-op for now — focus is UI-only in the WebView version.
            (void) owner;
        })

        // "setPlaying" — { playing: true/false }
        // No APVTS param called "playing" exists; the engine's _isPlaying flag
        // is set directly by DrawnCurveProcessor::setPlaying().  The previous
        // code looked up a non-existent parameter, so getParameter() returned
        // null and the engine stayed at its default _isPlaying=false — which
        // caused processLane() to early-out and swallow every per-lane render
        // (no audio out, no quantization, no Note-Ons).
        .withEventListener ("setPlaying", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const bool playing = static_cast<bool> (args[0]["playing"]);
            owner->proc.setPlaying (playing);
        })

        // "clearLane" — { lane: N }
        .withEventListener ("clearLane", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const int lane = static_cast<int> (args[0]["lane"]);
            owner->proc.clearSnapshot (lane);
        })

        // "addLane" — {}
        .withEventListener ("addLane", [owner] (const Array<var>&)
        {
            if (owner->proc.activeLaneCount < kMaxLanes)
            {
                ++owner->proc.activeLaneCount;
                owner->sendStateSnapshot();
            }
        })

        // "removeLane" — { lane: N }
        .withEventListener ("removeLane", [owner] (const Array<var>& args)
        {
            if (args.isEmpty()) return;
            const int lane = static_cast<int> (args[0]["lane"]);
            owner->proc.deleteLane (lane);
            owner->sendStateSnapshot();
        });
}

// ── Constructor / Destructor ──────────────────────────────────────────────────

WebCurveEditor::WebCurveEditor (DrawnCurveProcessor& p)
    : AudioProcessorEditor (p),
      proc (p),
      webView (buildOptions (this))
{
    addAndMakeVisible (webView);
    setSize (1024, 768);
    setResizable (true, false);

    // Listen to all APVTS parameters so we can forward changes to JS.
    const auto& params = proc.apvts.processor.getParameters();
    for (auto* param : params)
    {
        if (auto* p = dynamic_cast<juce::AudioProcessorParameterWithID*> (param))
        {
            proc.apvts.addParameterListener (p->paramID, this);
            listenedParams.add (p->paramID);
        }
    }

    // ── Standalone MIDI output ────────────────────────────────────────────────
    // Mirror the native editor's behaviour: when running as a standalone app,
    // create a virtual MIDI source called "DrawnQurve" and register it with
    // the processor.  Without this the engine's MIDI emission has nowhere to
    // go (both _virtualMidiOut and _directMidiOut stay null in the timer
    // path), which silently discards every Note On / CC / PB the engine
    // generates — that's what "no quantization" looked like from the outside.
    if (juce::JUCEApplicationBase::isStandaloneApp())
    {
        virtualMidiPort = juce::MidiOutput::createNewDevice ("DrawnQurve");
        if (virtualMidiPort != nullptr)
            proc.setVirtualMidiOutput (virtualMidiPort.get());
    }

    // Navigate to the resource provider root — triggers "uiReady" from JS
    // once the page has loaded and the bridge is initialised.
    webView.goToURL (juce::WebBrowserComponent::getResourceProviderRoot());

    // Start phase heartbeat at 30 Hz
    startTimer (33);
}

WebCurveEditor::~WebCurveEditor()
{
    stopTimer();
    for (const auto& id : listenedParams)
        proc.apvts.removeParameterListener (id, this);

    // Detach the virtual MIDI port from the processor BEFORE the unique_ptr
    // resets, so the audio/timer thread never reads a dangling pointer.
    proc.setVirtualMidiOutput (nullptr);
    proc.setDirectMidiOutput  (nullptr);
}

// ── Layout ────────────────────────────────────────────────────────────────────

void WebCurveEditor::resized()
{
    webView.setBounds (getLocalBounds());
}

// ── Phase timer ───────────────────────────────────────────────────────────────

void WebCurveEditor::timerCallback()
{
    if (! pageReady)
        return;

    const float phase = proc.currentPhase();   // exposed on DrawnCurveProcessor

    // Only emit if phase has moved meaningfully (avoids flooding when paused)
    if (std::abs (phase - lastSentPhase) < 0.001f)
        return;
    lastSentPhase = phase;

    webView.emitEventIfBrowserIsVisible ("phase", makeObj ({ { "phase", phase } }));
}

// ── Parameter listener ────────────────────────────────────────────────────────

void WebCurveEditor::parameterChanged (const juce::String& paramID, float newValue)
{
    if (! pageReady)
        return;

    // Forward every parameter change to JS in real time.
    // Keep the object on the message thread (parameterChanged may be called
    // from the audio thread on some hosts).
    juce::MessageManager::callAsync ([this, paramID, newValue]
    {
        if (! pageReady)
            return;
        webView.emitEventIfBrowserIsVisible ("paramChange",
            makeObj ({ { "id", paramID }, { "value", newValue } }));

        // Rebuild the engine snapshot(s) for the affected lane(s).  APVTS
        // atomics update on setValueNotifyingHost, but the audio thread reads
        // from a separate LaneSnapshot struct that's only refreshed by
        // updateLaneSnapshot().  Per-lane params hit one lane; global sync
        // params (syncEnabled / syncBeats) change loop length, so every lane
        // needs a refresh.
        if (paramID == ParamID::syncEnabled || paramID == ParamID::syncBeats)
        {
            for (int L = 0; L < proc.activeLaneCount; ++L)
                proc.updateLaneSnapshot (L);
        }
        else if (paramID.startsWith ("l"))
        {
            const int sep = paramID.indexOfChar ('_');
            if (sep > 1)
            {
                const int lane = paramID.substring (1, sep).getIntValue();
                if (lane >= 0 && lane < kMaxLanes)
                    proc.updateLaneSnapshot (lane);
            }
        }
    });
}

// ── State snapshot ────────────────────────────────────────────────────────────

void WebCurveEditor::sendStateSnapshot()
{
    // Build a complete state object and emit it so the JS can initialise
    // its React state from real APVTS values instead of the demo sine curves.

    juce::var lanesArr (juce::Array<juce::var>{});
    auto& lanesArrRef = *lanesArr.getArray();

    for (int L = 0; L < proc.activeLaneCount; ++L)
    {
        auto lane = std::make_unique<juce::DynamicObject>();

        lane->setProperty ("id",    L);
        lane->setProperty ("name",  "Lane " + juce::String (L + 1));

        // APVTS helpers.
        // getRawParameterValue returns ACTUAL values (not 0-1 normalised):
        //   AudioParameterChoice → choice index (0, 1, 2 …)
        //   AudioParameterInt    → integer value in its declared range
        //   AudioParameterFloat  → float in its declared range (smoothing/minOut/maxOut are 0-1)
        //   AudioParameterBool   → 0.0f or 1.0f
        const auto raw = [&] (const juce::String& suffix) -> float {
            if (auto* p = proc.apvts.getRawParameterValue (laneParam (L, suffix)))
                return p->load();
            jassertfalse;   // parameter ID not registered — check laneParam() format
            return 0.0f;
        };

        // scaleRoot / scaleMask are global (shared by all lanes) — no lane prefix.
        const auto globalRaw = [&] (const juce::String& id) -> float {
            if (auto* p = proc.apvts.getRawParameterValue (id))
                return p->load();
            jassertfalse;
            return 0.0f;
        };

        static const char* kTargets[4] = { "CC", "Aftertouch", "PitchBend", "Note" };
        const int msgType = juce::jlimit (0, 3, static_cast<int> (raw ("msgType")));
        lane->setProperty ("target",       kTargets[msgType]);
        lane->setProperty ("targetDetail", static_cast<int> (raw ("ccNumber")));   // 0-127
        lane->setProperty ("channel",      static_cast<int> (raw ("midiChannel")));// 1-16
        lane->setProperty ("smooth",       raw ("smoothing"));                     // 0-1
        lane->setProperty ("rangeMin",     raw ("minOutput"));                     // 0-1
        lane->setProperty ("rangeMax",     raw ("maxOutput"));                     // 0-1
        lane->setProperty ("velocity",     static_cast<int> (raw ("noteVelocity")));// 1-127
        lane->setProperty ("enabled",      raw ("enabled") > 0.5f);
        // Per-lane quantization (mirrors xQuantize/yQuantize/xDivisions/yDivisions APVTS).
        lane->setProperty ("quantizeX",    raw ("xQuantize") > 0.5f);
        lane->setProperty ("quantizeY",    raw ("yQuantize") > 0.5f);
        lane->setProperty ("xDivisions",   static_cast<int> (raw ("xDivisions")));   // 2-32
        lane->setProperty ("yDivisions",   static_cast<int> (raw ("yDivisions")));   // 2-24
        lane->setProperty ("scaleRoot",    static_cast<int> (globalRaw (ParamID::scaleRoot)));  // 0-11
        lane->setProperty ("scaleMask",    static_cast<int> (globalRaw (ParamID::scaleMask)));  // 0-4095
        lane->setProperty ("scaleId",      "chromatic");   // TODO: derive from mask

        // Curve data (Float32Array → JSON array of 256 floats)
        if (proc.hasCurve (L))
        {
            juce::var curveArr (juce::Array<juce::var>{});
            auto& ref = *curveArr.getArray();
            ref.resize (256);
            const auto table = proc.getCurveTable (L);
            for (int i = 0; i < 256; ++i)
                ref.set (i, table[static_cast<std::size_t> (i)]);
            lane->setProperty ("curve", curveArr);
        }
        else
        {
            lane->setProperty ("curve", juce::var());   // null
        }

        lanesArrRef.add (juce::var (lane.release()));
    }

    // Pull global transport state from APVTS so the JS UI starts in sync with
    // what the engine actually believes.  Hard-coding these created a silent
    // mismatch: the UI thought sync was on while APVTS::syncEnabled was off,
    // so the beats slider wrote to syncBeats but the engine kept using the
    // free-running 1 s loop length until the user toggled sync off→on.
    const bool   apvtsSyncOn   = proc.apvts.getRawParameterValue (ParamID::syncEnabled)->load() > 0.5f;
    const float  apvtsBeats    = proc.apvts.getRawParameterValue (ParamID::syncBeats)->load();
    const float  apvtsSpeed    = proc.apvts.getRawParameterValue (ParamID::playbackSpeed)->load();
    const int    apvtsDirIdx   = juce::jlimit (0, 2, static_cast<int> (
                                     proc.apvts.getRawParameterValue (ParamID::playbackDirection)->load()));
    static const char* const kDirNames[] = { "fwd", "rev", "pp" };

    const auto snap = makeObj ({
        { "lanes",           lanesArr },
        { "activeLaneCount", proc.activeLaneCount },
        { "phase",           proc.currentPhase() },
        { "playing",         true },
        { "direction",       kDirNames[apvtsDirIdx] },
        { "syncOn",          apvtsSyncOn },
        { "beats",           apvtsBeats },
        { "speed",           apvtsSpeed },
        { "focus",           0 },
    });

    webView.emitEventIfBrowserIsVisible ("stateSnapshot", snap);
}

void WebCurveEditor::sendCurveData (int lane)
{
    if (!proc.hasCurve (lane)) return;

    juce::var arr (juce::Array<juce::var>{});
    auto& ref = *arr.getArray();
    ref.resize (256);
    const auto table = proc.getCurveTable (lane);
    for (int i = 0; i < 256; ++i)
        ref.set (i, table[static_cast<std::size_t> (i)]);

    webView.emitEventIfBrowserIsVisible ("curveData",
        makeObj ({ { "lane", lane }, { "data", arr } }));
}
