#pragma once

/**
 * @file PluginEditor.h
 *
 * DrawnCurveEditor — JUCE AudioProcessorEditor for DrawnCurve AUv3.
 *
 * UI Layout (800 × 760 px)
 * ────────────────────────
 *   Utility bar (36 px)  : Sync · ≡LaneSync · FREE/speed · | ♯/♭ · Clear · Panic · Theme · ?
 *   ┌─────────────────────────────────────┬──────────────────────────┐
 *   │  Stage panel (476 px)               │  Right rail (296 px)     │
 *   │  Canvas + Y/X density steppers      │  FOCUSED LANE (full)     │
 *   │                                     │    Lane selector 1/2/3   │
 *   │                                     │    Direction             │
 *   │                                     │    Speed (per-lane) ×    │
 *   │                                     │    Range                 │
 *   │                                     │    Smooth / Phase        │
 *   │                                     │    ── LANES ──           │
 *   │                                     │    ∞/1  Matrix rows      │
 *   └─────────────────────────────────────┴──────────────────────────┘
 *   Musical zone — full width (44 px collapsed / 268 px expanded)
 */

#include <array>
#include <juce_audio_utils/juce_audio_utils.h>
#include "PluginProcessor.h"
#include "SegmentedControl.h"
#include "ScaleLattice.h"
#include "UI/ChromaticWheel.h"
#include "UI/IconFactory.h"
#include "ScaleData.h"
#include "BinaryData.h"   // generated by juce_add_binary_data (DrawnCurveFonts target)

//==============================================================================
/**
 * Colour palette tokens — single source of truth for the editor's UI chrome
 * (T2.9 visual-audit-2026-04 §4).  Two instances live in the .cpp:
 *   `kLight` — paper-warm, mirrors webapp/src/index.css `--paper-*` vars
 *   `kDark`  — deep navy/slate
 *
 * The split is deliberate:
 *   - Canvas tokens (background…panelBorder) are read by CurveDisplay,
 *     ScaleLattice, etc. via `currentTheme()`.
 *   - UI chrome tokens (textCol…lockColour) replace the dozens of inline
 *     `_lightMode ? Colour(0x…) : Colour(0x…)` ternaries that previously
 *     scattered the same palette across 30+ sites in PluginEditor.cpp.
 *
 * Adding a new theme (e.g. high-contrast "performance") in future means
 * defining one new `Theme` literal — no per-call-site editing.
 */
struct Theme
{
    // ── Canvas / panels (existing — read by CurveDisplay etc.) ───────────────
    juce::Colour background;     ///< Editor backdrop
    juce::Colour stageBg;        ///< Lane canvas background
    juce::Colour gridLine;       ///< Lane canvas grid
    juce::Colour curve;          ///< Default curve colour (overridden per-lane)
    juce::Colour capture;        ///< Live-capture stroke accent
    juce::Colour playhead;       ///< Playhead vertical line
    juce::Colour playheadDot;    ///< Playhead dot on a curve
    juce::Colour hint;           ///< Empty-canvas hint text
    juce::Colour border;         ///< Generic border (canvases + rules)
    juce::Colour panelBg;        ///< Right-rail panel background
    juce::Colour panelBorder;    ///< Right-rail panel border

    // ── UI chrome tokens (T2.9 — consolidated from inline ternaries) ─────────
    juce::Colour textCol;        ///< Primary label text (high contrast)
    juce::Colour dimText;        ///< Secondary / readout text (low contrast)
    juce::Colour btnBg;          ///< Default button background
    juce::Colour btnText;        ///< Default button text
    juce::Colour tbBg;           ///< Slider text-box background
    juce::Colour tbLine;         ///< Slider text-box outline
    juce::Colour accent;         ///< Lane-1 accent (slider thumbs etc.)
    juce::Colour chipOn;         ///< Selected subfamily chip
    juce::Colour chipOff;        ///< Unselected subfamily chip
    juce::Colour chipTextOn;     ///< Selected chip text
    juce::Colour chipTextOff;    ///< Unselected chip text
    juce::Colour famActive;      ///< Active family-tab highlight (strong)
    juce::Colour famBrowsed;     ///< Recognised-but-not-active family tab
    juce::Colour famInactive;    ///< Other family tabs
    juce::Colour famTextOff;     ///< Inactive family-tab text
    juce::Colour lockColour;     ///< X/Y lock + #-combo accent
};

//==============================================================================
/**
 * Shared visual metrics for the editor's three modal overlays:
 *   `_scaleOverlay`, `_routingOverlay`, `helpOverlay`.
 * T2.8 (visual-audit-2026-04 §4): one elevated-panel treatment — same
 * radius, border, soft shadow, and dim-backdrop opacity — so all three
 * read as the same kind of object.  Single source of truth lets future
 * tuning ripple through one place.
 *
 * The helpers `paintBackdrop()` / `paintPanel()` keep each overlay's
 * paint() down to two calls plus its own content rendering.
 */
namespace dcui::OverlayChrome
{
    /** Panel corner radius — splits the difference between the previous
     *  10 px (RoutingOverlay) and 12 px (ScaleOverlay) treatments. */
    inline constexpr float kPanelRadius      = 11.0f;

    /** Hairline panel border. */
    inline constexpr float kPanelBorderWidth = 1.0f;

    /** Soft drop-shadow blur radius (px). */
    inline constexpr int   kShadowRadius     = 14;

    /** Dim-backdrop alpha (0–255).  Light mode lifts the panel against a
     *  cream editor; dark mode needs a heavier dim against deep slate. */
    inline constexpr juce::uint8 kBackdropAlphaLight = 0x60;
    inline constexpr juce::uint8 kBackdropAlphaDark  = 0x80;

    inline juce::Colour panelBg     (bool light) noexcept
    { return light ? juce::Colour (0xfffaf8f5) : juce::Colour (0xff1e1e2a); }

    inline juce::Colour panelBorder (bool light) noexcept
    { return light ? juce::Colour (0xffccc8c0) : juce::Colour (0xff3a3a4a); }

    inline juce::Colour shadowCol   (bool light) noexcept
    { return juce::Colour::fromRGBA (0, 0, 0, light ? juce::uint8 (0x55) : juce::uint8 (0x88)); }

    inline juce::Colour backdrop    (bool light) noexcept
    {
        const juce::uint8 a = light ? kBackdropAlphaLight : kBackdropAlphaDark;
        return juce::Colour::fromRGBA (0, 0, 0, a);
    }

    /** Fills `fullArea` with the dim-backdrop colour. */
    inline void paintBackdrop (juce::Graphics& g, bool light, juce::Rectangle<int> fullArea)
    {
        g.setColour (backdrop (light));
        g.fillRect (fullArea);
    }

    /** Paints a soft shadow + filled panel + border at `panel`.
     *  No-op for empty rects (so overlays can call this unconditionally). */
    inline void paintPanel (juce::Graphics& g, bool light, juce::Rectangle<float> panel)
    {
        if (panel.isEmpty()) return;

        // Soft drop-shadow lifts the panel off the dim backdrop.
        juce::DropShadow (shadowCol (light), kShadowRadius, juce::Point<int> (0, 2))
            .drawForRectangle (g, panel.toNearestInt());

        g.setColour (panelBg (light));
        g.fillRoundedRectangle (panel, kPanelRadius);

        g.setColour (panelBorder (light));
        g.drawRoundedRectangle (panel.reduced (0.5f), kPanelRadius, kPanelBorderWidth);
    }
}

//==============================================================================
/**
 * App-level LookAndFeel — delivers the v2 Studio typography (Domine serif,
 * Inter Tight sans, Caveat hand) bundled as JUCE BinaryData.  Routing happens
 * inside getTypefaceForFont() based on a sentinel name embedded in
 * FontOptions::withName() by the makeXxxFont() factories below:
 *
 *   "DC-Serif"        → Domine.ttf            (italic synthesised by JUCE)
 *   "DC-Sans"         → InterTight.ttf
 *   "DC-Sans-Italic"  → InterTight-Italic.ttf
 *   "DC-Hand"         → Caveat.ttf
 *
 * Anything else (the JUCE default sans-serif name, third-party widgets, etc.)
 * falls through to InterTight so the whole editor reads as v2 Studio.
 *
 * Each typeface is loaded once, lazily, and cached for process lifetime.
 *
 * All widget-specific LookAndFeel subclasses inside DrawnCurveEditor inherit
 * from this class so they all get the same font routing.
 */
class DrawnCurveLookAndFeel : public juce::LookAndFeel_V4
{
public:
    // ── Sentinel font names (used by FontOptions::withName + routed below) ──
    static constexpr const char* kSerifName       = "DC-Serif";
    static constexpr const char* kSansName        = "DC-Sans";
    static constexpr const char* kSansItalicName  = "DC-Sans-Italic";
    static constexpr const char* kHandName        = "DC-Hand";

    // ── T2.9 (visual-audit-2026-04 §4): single source of truth for UI palette ──
    /** Returns the palette for the current mode.  Replaces inline
     *  `_lightMode ? Colour(0x…) : Colour(0x…)` ternaries scattered throughout
     *  PluginEditor.cpp.  Callers cache the const-ref locally and read the
     *  named tokens (e.g. `t.btnBg`, `t.dimText`).  Defined in
     *  PluginEditor.cpp where the kLight/kDark literals live. */
    static const Theme& theme (bool light) noexcept;

    DrawnCurveLookAndFeel()
    {
        // Make Inter Tight the implicit default so any LookAndFeel-wide query
        // for the sans-serif family also routes to our bundled typeface.
        setDefaultSansSerifTypefaceName (kSansName);
    }

    /** Route font requests to one of the four bundled typefaces based on the
     *  sentinel name set by makeXxxFont().  Style flags (italic / bold) are
     *  applied by JUCE on top of the returned typeface; for Domine (no italic
     *  master) this synthesises italic by skewing — matching the webapp, which
     *  also lacks a true Domine italic. */
    juce::Typeface::Ptr getTypefaceForFont (const juce::Font& f) override
    {
        const auto name = f.getTypefaceName();

        if (name == kSerifName)        return serifTypeface();
        if (name == kHandName)         return handTypeface();
        if (name == kSansItalicName)   return sansItalicTypeface();
        if (name == kSansName)         return sansTypeface();

        // JUCE default sans-serif requests + everything else → Inter Tight.
        return sansTypeface();
    }

    juce::Font getLabelFont (juce::Label&) override
    {
        return makeSansFont (12.0f);
    }

    juce::Font getTextButtonFont (juce::TextButton&, int buttonHeight) override
    {
        return makeSansFont (juce::jmin (14.0f, (float) buttonHeight * 0.55f));
    }

    juce::Font getComboBoxFont (juce::ComboBox&) override
    {
        return makeSansFont (13.0f);
    }

    /** T1.2 (visual-audit-2026-04 §3 P6): bump the slider thumb radius so
     *  performance-hot range / speed sliders are easier to grab on iPad.
     *  JUCE's default caps at 12 → 24 px diameter; we raise the floor to 14
     *  → 28 px diameter, still constrained by the slider's own height so
     *  shorter sliders elsewhere aren't overrun.  */
    int getSliderThumbRadius (juce::Slider& slider) override
    {
        const int axisExtent = slider.isHorizontal() ? slider.getHeight()
                                                     : slider.getWidth();
        return juce::jmin (16, axisExtent / 2);
    }

    // ── Font factories ──────────────────────────────────────────────────────
    //
    // Use these everywhere a juce::Font is needed.  They set a sentinel name
    // on FontOptions which getTypefaceForFont() routes to a bundled .ttf.
    //
    // We deliberately do NOT call FontOptions::withTypeface() here:
    //   • withTypeface embeds a size-0 typeface directly into the Font, which
    //     bypasses JUCE's per-render sizing and breaks Unicode shaping.
    //   • A later fallback call to withTypeface() on the same FontOptions
    //     fires jassert(x == nullptr || style.isEmpty()) in juce_FontOptions.h.
    // withFallbackEnabled is set so CoreText substitutes any code points the
    // bundled font delegates (emoji, rare scripts, etc.).

    /** Sans body — Inter Tight (regular or true italic). */
    static juce::Font makeSansFont (float height, bool italic = false)
    {
        return juce::Font (juce::FontOptions{}
                               .withName (italic ? kSansItalicName : kSansName)
                               .withHeight (height)
                               .withFallbackEnabled (true));
    }

    /** Serif accent — Domine.  Italic is synthesised by JUCE (no italic
     *  master in the .ttf, matching the webapp). */
    static juce::Font makeSerifFont (float height, bool italic = false)
    {
        auto f = juce::Font (juce::FontOptions{}
                                 .withName (kSerifName)
                                 .withHeight (height)
                                 .withFallbackEnabled (true));
        return italic ? f.italicised() : f;
    }

    /** Handwriting — Caveat (used sparingly: hint text, captures, etc.). */
    static juce::Font makeHandFont (float height)
    {
        return juce::Font (juce::FontOptions{}
                               .withName (kHandName)
                               .withHeight (height)
                               .withFallbackEnabled (true));
    }

    /** Backward-compat alias — old call sites that requested "the" font
     *  (sans, regular weight) still work without modification. */
    static juce::Font makeFont (float height) { return makeSansFont (height); }

private:
    // ── Process-lifetime typeface cache ─────────────────────────────────────
    //
    // Each typeface is created from BinaryData on first request and held for
    // the lifetime of the process.  Safe inside the AUv3 XPC sandbox because
    // BinaryData lives in the plugin binary itself (no filesystem access).

    static const juce::Typeface::Ptr& serifTypeface()
    {
        static const juce::Typeface::Ptr instance =
            juce::Typeface::createSystemTypefaceFor (BinaryData::Domine_ttf,
                                                     BinaryData::Domine_ttfSize);
        return instance;
    }

    static const juce::Typeface::Ptr& sansTypeface()
    {
        static const juce::Typeface::Ptr instance =
            juce::Typeface::createSystemTypefaceFor (BinaryData::InterTight_ttf,
                                                     BinaryData::InterTight_ttfSize);
        return instance;
    }

    static const juce::Typeface::Ptr& sansItalicTypeface()
    {
        // juce_add_binary_data strips '-' from filenames (and converts '.' → '_'):
        // InterTight-Italic.ttf  →  BinaryData::InterTightItalic_ttf
        static const juce::Typeface::Ptr instance =
            juce::Typeface::createSystemTypefaceFor (BinaryData::InterTightItalic_ttf,
                                                     BinaryData::InterTightItalic_ttfSize);
        return instance;
    }

    static const juce::Typeface::Ptr& handTypeface()
    {
        static const juce::Typeface::Ptr instance =
            juce::Typeface::createSystemTypefaceFor (BinaryData::Caveat_ttf,
                                                     BinaryData::Caveat_ttfSize);
        return instance;
    }
};

// ---------------------------------------------------------------------------
// Lane colour/stroke identifiers — used by CurveDisplay and routing matrix.
// ---------------------------------------------------------------------------

/// Lane colours (light mode) — v2 Studio palette.
/// Lanes 0–2 mirror the webapp's ink-blue / terracotta / moss trio
/// (--lane-1, --lane-2, --lane-3 in src/index.css).  Lane 3 (JUCE-only)
/// adds a muted plum that sits naturally in the same paper aesthetic.
static const juce::Colour kLaneColourLight[kMaxLanes] =
{
    juce::Colour (0xff3A4866),   // Lane 0 — ink-blue
    juce::Colour (0xffC45F43),   // Lane 1 — terracotta
    juce::Colour (0xff5B8A64),   // Lane 2 — moss
    juce::Colour (0xff6B4F7C),   // Lane 3 — plum (JUCE-only 4th lane)
};

/// Lane colours (dark mode) — brighter siblings of the light palette,
/// keeping the same hue family so a lane reads as the same lane in either theme.
static const juce::Colour kLaneColourDark[kMaxLanes] =
{
    juce::Colour (0xff4A90E2),   // Lane 0 — bright blue (mirrors webapp dark)
    juce::Colour (0xffE8A838),   // Lane 1 — amber (mirrors webapp dark)
    juce::Colour (0xff5CB85C),   // Lane 2 — green (mirrors webapp dark)
    juce::Colour (0xffB888D4),   // Lane 3 — light plum (JUCE-only 4th lane)
};

//==============================================================================
/**
 * Interactive display of all lane curves, playhead, grid, and axis labels.
 *
 * Renders each lane's curve with a distinct colour and stroke texture.
 * The focused lane is drawn at full opacity; other lanes at 40%.
 * Drawing (mouseDown / Drag / Up) always targets the focused lane.
 */
class CurveDisplay : public juce::Component,
                     public juce::Timer
{
public:
    explicit CurveDisplay (DrawnCurveProcessor& p);
    ~CurveDisplay() override;

    void paint     (juce::Graphics&)          override;
    void resized   ()                         override;
    void mouseDown (const juce::MouseEvent&)  override;
    void mouseDrag (const juce::MouseEvent&)  override;
    void mouseUp   (const juce::MouseEvent&)  override;
    void timerCallback()                      override;

    void setLightMode   (bool light);
    void setFocusedLane (int lane)  { _focusedLane = lane; repaint(); }
    int  getFocusedLane()    const  { return _focusedLane; }
    void setUseFlats    (bool b)    { _useFlats = b; repaint(); }

    void setXDivisions (int n) { _xDivisions = juce::jlimit (2, 32, n); repaint(); }
    void setYDivisions (int n) { _yDivisions = juce::jlimit (2, 24, n); repaint(); }
    int  getXDivisions() const { return _xDivisions; }
    int  getYDivisions() const { return _yDivisions; }

    std::function<void()> onBadgeTap;    ///< Called when the scale badge is tapped
    std::function<void()> onCurveDrawn; ///< Called when a gesture is finalized (mouseUp)

private:
    juce::Rectangle<int> _badgeRect;    ///< Updated each paint(); used for tap detection
    DrawnCurveProcessor& proc;
    double     captureStartTime { 0.0   };
    bool       isCapturing      { false };
    bool       _lightMode       { true  };
    int        _focusedLane     { 0     };
    int        _xDivisions      { 4 };
    int        _yDivisions      { 4 };
    bool       _blinkOn         { true  };   ///< Toggled by _blinkCounter to drive pause blink
    int        _blinkCounter    { 0     };   ///< Incremented each timer tick; wraps at kBlinkPeriod
    static constexpr int kBlinkPeriod = 12; ///< Timer ticks per blink half-cycle (~1.25 Hz at 30 Hz)
    bool       _useFlats        { false };   ///< Mirror of editor flag; controls note name rendering
    juce::Path capturePath;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (CurveDisplay)
};

//==============================================================================
class HelpOverlay : public juce::Component
{
public:
    HelpOverlay();
    void paint     (juce::Graphics&) override;
    void mouseDown (const juce::MouseEvent&) override;
    void setLightMode (bool light) { _lightMode = light; repaint(); }

private:
    bool _lightMode { true  };
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (HelpOverlay)
};

/**
 * TwoValueHorizontal slider that supports dragging the track (not the thumbs)
 * to shift the entire range. Tapping/dragging near a thumb still moves that
 * thumb individually (standard behaviour via the base class).
 */
/**
 * Two-thumb horizontal range slider with whole-range drag support.
 *
 * Standard TwoValueHorizontal behaviour:
 *   Tap/drag within kThumbHitRadius px of the min or max thumb → moves that thumb alone.
 *
 * Range-drag behaviour (replaces JUCE's default "snap nearest thumb" on track tap):
 *   Tap/drag anywhere on the track that is NOT near either thumb → shifts both thumbs by
 *   the same delta, preserving the span.  Both ends are clamped to [minimum, maximum]
 *   so the span shrinks at the extremes.
 *
 * Practical use (DrawnCurve):
 *   The range slider maps [minOutput, maxOutput] → MIDI output range.
 *   Dragging the track transposes a Note-mode lane or shifts a CC/PB band.
 *   Grabbing a thumb adjusts only that boundary.
 */
class DualRangeSlider : public juce::Slider
{
public:
    DualRangeSlider() { setSliderStyle (juce::Slider::TwoValueHorizontal); }

    void mouseDown (const juce::MouseEvent& e) override
    {
        _rangeDragging = false;
        if (isThumbHit (e.x))
        {
            juce::Slider::mouseDown (e);
            return;
        }
        _dragStartMin = getMinValue();
        _dragStartMax = getMaxValue();
        _dragStartX   = e.x;
        _rangeDragging = true;
    }

    void mouseDrag (const juce::MouseEvent& e) override
    {
        if (! _rangeDragging) { juce::Slider::mouseDrag (e); return; }
        const double delta = (e.x - _dragStartX) / (double) getWidth()
                             * (getMaximum() - getMinimum());
        // Each thumb clamps independently — span shrinks at walls (sticky-wall behaviour).
        setMinValue (juce::jlimit (getMinimum(), getMaximum(), _dragStartMin + delta),
                     juce::sendNotificationSync);
        setMaxValue (juce::jlimit (getMinimum(), getMaximum(), _dragStartMax + delta),
                     juce::sendNotificationSync);
    }

    void mouseUp (const juce::MouseEvent& e) override
    {
        if (! _rangeDragging) { juce::Slider::mouseUp (e); return; }
        _rangeDragging = false;
    }

private:
    bool   _rangeDragging { false };
    double _dragStartMin  { 0.0 };
    double _dragStartMax  { 1.0 };
    int    _dragStartX    { 0 };
    // T1.2 (visual-audit-2026-04 §3 P6): hit radius matches the enlarged
    // visible thumb (16 px radius via DrawnCurveLookAndFeel::getSliderThumbRadius).
    static constexpr int kThumbHitRadius = 22;

    bool isThumbHit (int px) const
    {
        const auto range = getMaximum() - getMinimum();
        if (range <= 0.0) return false;
        const float minPx = static_cast<float> (
            (getMinValue() - getMinimum()) / range * getWidth());
        const float maxPx = static_cast<float> (
            (getMaxValue() - getMinimum()) / range * getWidth());
        return std::abs (px - (int)minPx) <= kThumbHitRadius
            || std::abs (px - (int)maxPx) <= kThumbHitRadius;
    }

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (DualRangeSlider)
};

// Forward declaration — RoutingOverlay is defined below DrawnCurveEditor.
class DrawnCurveEditor;

//==============================================================================
/**
 * Drop-down routing panel shown when the user taps a lane's msg-type button.
 *
 * The overlay fills the full editor bounds (transparent outside the panel rect)
 * so it intercepts mouse events everywhere and dismisses on a tap outside the
 * panel.  All routing child components live inside this component so z-ordering
 * is clean (no separate parent-repaint coordination needed).
 */
class RoutingOverlay : public juce::Component
{
public:
    explicit RoutingOverlay (DrawnCurveEditor& owner);
    ~RoutingOverlay() override;

    void paint   (juce::Graphics&)          override;
    void resized ()                         override;
    void mouseDown (const juce::MouseEvent&) override;

    /// Show the single-lane routing panel anchored below anchorBounds.
    void showForLane (int lane, juce::Rectangle<int> anchorBoundsInEditor);

    /// Show the all-lanes mini-matrix panel anchored below anchorBounds.
    void showForAllLanes (juce::Rectangle<int> anchorBoundsInEditor);

    /// Hide the panel.
    void dismiss();

    /// Reposition the panel when the editor is resized, without recreating APVTS attachments.
    /// Safe to call whether in single-lane or all-lanes mode.
    void reanchor (juce::Rectangle<int> anchorBoundsInEditor);

    void setLightMode (bool light);

    /// -1 = all-lanes mode, 0..kMaxLanes-1 = individual lane.
    int activeLane() const noexcept { return _lane; }

private:
    DrawnCurveEditor& _owner;
    int               _lane      { 0 };
    bool              _lightMode { true };
    juce::Rectangle<int> _panelRect;   ///< Panel bounds in local (overlay) coords

    // ── Single-lane panel components ─────────────────────────────────────────
    juce::TextButton ccBtn;     ///< msg type: CC
    juce::TextButton atBtn;     ///< msg type: AT
    juce::TextButton pbBtn;     ///< msg type: PB
    juce::TextButton noteBtn;   ///< msg type: Note (♩ — text set in constructor)

    juce::Label  detailLabel;    ///< "CC 74" / "Vel 100"
    juce::Label  channelLabel;   ///< "Ch 1"

    juce::TextButton teachBtn;    ///< MIDI learn
    juce::TextButton muteBtn;     ///< lane pause
    juce::TextButton oneShotBtn;  ///< ↦/↺ toggle — one-shot (lit) vs loop (unlit)
    juce::TextButton legatoBtn;   ///< tie symbol toggle — legato note overlap

    juce::Slider phaseSlider;
    juce::Label  phaseLabel;
    std::unique_ptr<juce::AudioProcessorValueTreeState::SliderAttachment> _phaseAttach;

    // ── All-lanes mini matrix (shown when invoked from the ✤ tab) ────────────
    std::array<juce::TextButton, kMaxLanes> rowTypeBtn;   ///< one msg-type button per lane
    std::array<juce::Label,      kMaxLanes> rowDetailLbl; ///< CC# / vel per lane
    std::array<juce::Label,      kMaxLanes> rowChanLbl;   ///< channel per lane

    void applyTheme();
    void showSingleLaneMode (bool visible);   ///< show/hide single-lane components
    void showAllLanesMode   (bool visible);   ///< show/hide all-lanes matrix components
    void updateMsgTypeHighlight();
    void updateDetailLabels();
    void cycleToMsgType (MessageType t);

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (RoutingOverlay)
};

//==============================================================================
/**
 * Main plugin editor window.
 */
class DrawnCurveEditor : public juce::AudioProcessorEditor,
                         private juce::AudioProcessorValueTreeState::Listener,
                         private juce::Timer
{
public:
    explicit DrawnCurveEditor (DrawnCurveProcessor&);
    ~DrawnCurveEditor() override;

    void paint   (juce::Graphics&) override;
    void resized ()                override;
    bool keyPressed (const juce::KeyPress&) override;

private:
    /// T2.4 (visual-audit-2026-04 §2.3, §4): when no lane has a stroke yet,
    /// dim the left-rail Y-stepper + bottom X-stepper so canvas chrome
    /// doesn't outweigh canvas content at first paint. Timer polls
    /// `proc.anyLaneHasCurve()` and fires `applyEmptyCanvasAlpha` only on
    /// transitions, so per-frame cost is a single bool comparison.
    void timerCallback() override;
    void applyEmptyCanvasAlpha (bool empty);
    bool _canvasWasEmpty { true };

private:
    // ── Custom LookAndFeels ───────────────────────────────────────────────────

    struct SymbolLF : public DrawnCurveLookAndFeel
    {
        // T2.1 (visual-audit-2026-04 §3 P4 / §4): unified pill chrome shared
        // with subfamily chips and segmented controls (dcui::ChipChrome).
        // Replaces JUCE's vertical-gradient pillule background so every
        // chip / tab / segmented control reads as one visual family.
        // Active state = solid `buttonOnColourId` fill instead of a halo.
        void drawButtonBackground (juce::Graphics& g, juce::Button& btn,
                                   const juce::Colour& bgColour,
                                   bool highlight, bool down) override
        {
            const auto r   = btn.getLocalBounds().toFloat().reduced (0.5f);
            const float cr = r.getHeight() * dcui::ChipChrome::kRadiusFactor;

            auto fill = bgColour;
            if (down)      fill = fill.contrasting (0.10f);
            else if (highlight) fill = fill.contrasting (0.05f);

            g.setColour (fill);
            g.fillRoundedRectangle (r, cr);

            // Hairline outline — matches SegmentedControl border.
            g.setColour (btn.findColour (juce::TextButton::textColourOffId)
                            .withMultipliedAlpha (0.20f));
            g.drawRoundedRectangle (r, cr, dcui::ChipChrome::kOutlineWidth);
        }

        void drawButtonText (juce::Graphics& g, juce::TextButton& btn,
                             bool, bool) override
        {
            const auto b = btn.getLocalBounds().toFloat().reduced (3.0f, 2.0f);
            if (b.isEmpty()) return;    // guard: tiny button → skip to avoid assertion
            g.setColour (btn.findColour (juce::TextButton::textColourOffId));
            g.setFont (DrawnCurveLookAndFeel::makeFont (12.0f));  // fallback chain included
            g.drawFittedText (btn.getButtonText(), b.toNearestInt(),
                              juce::Justification::centred, 1);
        }
    };
    SymbolLF _symbolLF;

    /// LookAndFeel for beat preset buttons: keeps background unchanged when
    /// disabled (only dims text), so disabled buttons don't go dark in light
    /// mode or lose contrast in dark mode.
    struct PresetBtnLF : public DrawnCurveLookAndFeel
    {
        void drawButtonBackground (juce::Graphics& g, juce::Button& btn,
                                   const juce::Colour& bgColour,
                                   bool highlight, bool down) override
        {
            auto r   = btn.getLocalBounds().toFloat().reduced (0.5f);
            auto col = bgColour;
            if (highlight) col = col.contrasting (0.05f);
            if (down)      col = col.contrasting (0.10f);
            g.setColour (col);
            g.fillRoundedRectangle (r, 4.0f);
        }

        void drawButtonText (juce::Graphics& g, juce::TextButton& btn,
                             bool, bool) override
        {
            const float alpha = btn.isEnabled() ? 1.0f : 0.28f;
            g.setColour (btn.findColour (juce::TextButton::textColourOffId)
                            .withMultipliedAlpha (alpha));
            g.setFont (DrawnCurveLookAndFeel::makeFont (11.0f));
            g.drawFittedText (btn.getButtonText(),
                              btn.getLocalBounds().reduced (2, 1),
                              juce::Justification::centred, 1);
        }
    };
    PresetBtnLF _presetBtnLF;

    /// LookAndFeel that draws a dcui icon instead of text — applied to
    /// TextButton arrays (mute, teach) that cannot be changed to IconButton
    /// without structural changes.
    struct IconDrawLF : public DrawnCurveLookAndFeel
    {
        dcui::IconType iconType { dcui::IconType::mute };

        void drawButtonBackground (juce::Graphics& g, juce::Button& btn,
                                   const juce::Colour&, bool, bool) override
        {
            const auto r     = btn.getLocalBounds().toFloat().reduced (0.5f);
            const bool tog   = btn.getToggleState();
            const auto bg    = btn.findColour (juce::TextButton::buttonColourId);
            const auto hlBg  = btn.findColour (juce::TextButton::buttonOnColourId);
            g.setColour (tog ? hlBg : bg);
            g.fillRoundedRectangle (r, 4.0f);
        }

        void drawButtonText (juce::Graphics& g, juce::TextButton& btn,
                             bool isHover, bool) override
        {
            const bool tog = btn.getToggleState();
            auto col = btn.findColour (tog ? juce::TextButton::textColourOnId
                                           : juce::TextButton::textColourOffId);
            if (isHover) col = col.brighter (0.18f);
            const auto iconBounds = btn.getLocalBounds().toFloat().reduced (5.0f, 5.0f);
            if (iconBounds.isEmpty()) return;   // guard: tiny button → skip
            dcui::IconFactory::drawIcon (g, iconType, iconBounds, col);
        }
    };
    IconDrawLF _muteDrawLF;
    IconDrawLF _teachDrawLF;

    struct DensityLF : public DrawnCurveLookAndFeel
    {
        void drawButtonText (juce::Graphics& g, juce::TextButton& btn,
                             bool, bool) override
        {
            const auto  text    = btn.getButtonText();
            const bool  isX     = text.startsWithChar ('X');
            const bool  isDense = text.endsWithChar   ('+');
            const auto  col     = btn.findColour (juce::TextButton::textColourOffId);
            const auto  b       = btn.getLocalBounds().toFloat().reduced (4.0f, 5.0f);
            if (b.isEmpty()) return;    // guard: avoid assertion with negative rect
            const int   n       = isDense ? 5 : 3;
            g.setColour (col);
            for (int i = 0; i < n; ++i)
            {
                const float t = (i + 0.5f) / static_cast<float> (n);
                if (!isX) { const float y = b.getY() + b.getHeight() * t;
                            g.drawLine (b.getX(), y, b.getRight(), y, 1.3f); }
                else       { const float x = b.getX() + b.getWidth() * t;
                            g.drawLine (x, b.getY(), x, b.getBottom(), 1.3f); }
            }
        }
    };
    DensityLF _densityLF;

    /// App-level LookAndFeel — set on the editor so all child components that
    /// don't have their own LF inherit it.  Must be declared before any
    /// component that might reference it during construction.
    DrawnCurveLookAndFeel _appLF;

    // ── Core references ───────────────────────────────────────────────────────
    DrawnCurveProcessor& proc;
    CurveDisplay   curveDisplay;
    HelpOverlay    helpOverlay;
    RoutingOverlay _routingOverlay;   ///< Drop-down routing panel (initially hidden)

    // ── Utility bar ───────────────────────────────────────────────────────────
    juce::TextButton playButton  { "Play"  };
    dcui::IconButton clearButton { "Clear", dcui::IconType::clearGesture };
    juce::TextButton panicButton { "!"     };
    juce::TextButton themeButton { "Dark"  };
    dcui::IconButton syncButton  { "Sync", dcui::IconType::sync };
    juce::TextButton helpButton  { "?"     };

    // ── Transport: direction + sync ───────────────────────────────────────────
    SegmentedControl dirControl;
    static constexpr int kDirParamToVis[3] = { 2, 0, 1 };
    static constexpr int kDirVisToParam[3] = { 1, 2, 0 };

    // ── Canvas density + quantization ─────────────────────────────────────────
    juce::TextButton tickYMinusBtn { "Y-" };
    juce::TextButton tickYPlusBtn  { "Y+" };
    juce::TextButton tickXMinusBtn { "X-" };
    juce::TextButton tickXPlusBtn  { "X+" };
    dcui::IconButton xQuantizeBtn  { "xQuantize", dcui::IconType::lock };   ///< Toggle X-axis (time) quantization
    dcui::IconButton yQuantizeBtn  { "yQuantize", dcui::IconType::lock };   ///< Toggle Y-axis (pitch/value) quantization
    juce::TextButton xyLockBtn     { "#" };                                 ///< Combo: activate both X + Y quantize at once

    // ── Beat subdivision + duration presets (sync mode, X-axis row) ──────────
    static constexpr int kNumXStepPresets    = 7;
    static constexpr int kNumSyncBeatsPresets = 6;
    std::array<juce::TextButton, kNumXStepPresets>     xStepPresetBtns;
    std::array<juce::TextButton, kNumSyncBeatsPresets> syncBeatsPresetBtns;

    // ── Y-axis presets (mode-dependent, Y-axis column) ────────────────────────
    // Note mode: octave range (1,2,3,4,8) + semitone step (1,2,3,4,5)
    // CC/Pressure: dozen range (12,24,36,48,60,72) + value step (1,2,3,4,6)
    static constexpr int kNumYOctavePresets   = 5;
    static constexpr int kNumYNoteStepPresets = 5;
    static constexpr int kNumYDozenPresets    = 6;
    static constexpr int kNumYCCStepPresets   = 5;
    static constexpr int kNumYPBRangePresets  = 4;  // PitchBend: 4k, 3k, 2k, 1k (k=2048)
    static constexpr int kNumYPBStepPresets   = 4;  // PitchBend step: 64, 128, 256, 512 PB units
    std::array<juce::TextButton, kNumYOctavePresets>   yOctavePresetBtns;
    std::array<juce::TextButton, kNumYNoteStepPresets> yNoteStepPresetBtns;
    std::array<juce::TextButton, kNumYDozenPresets>    yDozenPresetBtns;
    std::array<juce::TextButton, kNumYCCStepPresets>   yCCStepPresetBtns;
    std::array<juce::TextButton, kNumYPBRangePresets>  yPBRangePresetBtns;
    std::array<juce::TextButton, kNumYPBStepPresets>   yPBStepPresetBtns;

    // ── Shared speed slider + attachment ─────────────────────────────────────
    juce::Slider speedSlider;      ///< Global speed — always in utility bar
    juce::Label  speedLabel;
    using Attach = juce::AudioProcessorValueTreeState::SliderAttachment;
    std::unique_ptr<Attach> speedAttach;

    // ── Per-lane speed slider (focused lane panel, below direction control) ───
#if defined(DC_HAVE_PER_LANE_PLAYBACK_PARAMS)
    juce::Slider laneSpeedSlider;  ///< Per-lane speed multiplier
    juce::Label  laneSpeedLabel;
    std::unique_ptr<Attach> laneSpeedAttach;
#endif

    // ── Shaping panel — per focused lane ─────────────────────────────────────
    SegmentedControl laneFocusCtrl;   ///< Lane 1 | Lane 2 | Lane 3

    juce::TextButton oneShotBtn;            ///< Loop (∞) / One-shot (1) — shaping panel
    juce::TextButton laneSyncBtn;           ///< Lock all lane playheads to the same phase
    juce::Slider     smoothingSlider;
    DualRangeSlider  rangeSlider;           ///< Track-drag shifts both thumbs together
    juce::Slider     phaseOffsetSlider;
    juce::Label  smoothingLabel, rangeLabel, phaseOffsetLabel;
    std::unique_ptr<Attach> smoothingAttach;
    std::unique_ptr<Attach> phaseOffsetAttach;

    // ── Routing matrix — one row per lane ─────────────────────────────────────
    // Each row: type button | detail label | channel label | teach | mute
    // laneTypeBtn cycles through CC/PB/Note/Aft on click; right-click = popup menu.
    std::array<juce::TextButton, kMaxLanes> laneTypeBtn;
    std::array<juce::Label,      kMaxLanes> laneDetailLabel;
    std::array<juce::Label,      kMaxLanes> laneChannelLabel;
    std::array<juce::TextButton, kMaxLanes> laneTeachBtn;
    std::array<juce::TextButton, kMaxLanes> laneMuteBtn;

    /// One-line detail text below the matrix rows: e.g. "CC 74 · Ch 1"
    juce::Label mappingDetailLabel;

    /// Transparent hit-area buttons drawn over lane colour dots in the matrix.
    /// Click → setFocusedLane(L).
    std::array<juce::TextButton, kMaxLanes> laneSelectBtn;

    /// "+" button that appears below the last active lane row when more lanes are available.
    juce::TextButton addLaneBtn;
    /// "-" button that appears next to addLaneBtn; removes the last active lane.
    juce::TextButton deleteLaneBtn;

    /// Tick-count readout labels shown between the density stepper buttons.
    juce::Label tickXCountLabel, tickYCountLabel;
    /// Step-size annotation: semitones (Y/Note) or seconds/beats (X). Hidden when not applicable.
    juce::Label yTickStepLabel, xTickStepLabel;

    // ── Notes editor — family browser (visible in Note mode) ─────────────────

    // Family tab bar — one button per dcScale family.
    std::array<juce::TextButton, dcScale::kNumFamilies> familyBtns;

    // Subfamily chips — one per mode in the active family.
    //
    // Option-B refactor (2026-04): the chip's miniature 5+7 lattice was removed.
    // At kSubfamilyRowH = 28 px, the dots became unreadable, and the v2 specs
    // call them "visual hints" — selection state is conveyed by the chip's
    // background colour (chipOn vs chipOff) instead.  SubfamilyLF retains the
    // mask field so that future variants (a long-press preview, a tooltip, or
    // a re-introduced minimap at a larger size) can use it without re-plumbing.
    static constexpr int kMaxModes = 11;   // Chordal is the largest family (11 entries)

    struct SubfamilyLF : public DrawnCurveLookAndFeel
    {
        uint16_t     mask   { 0xAD5 };   ///< retained for tooltip / future preview use
        juce::Colour colOn  { 0xffC9D6E3 };
        juce::Colour colOff { 0xff2A3340 };

        // T2.1 (visual-audit-2026-04 §3 P4 / §4): unified pill chrome —
        // identical treatment to SymbolLF / SegmentedControl so chips,
        // family tabs and segmented controls all read as one visual family.
        void drawButtonBackground (juce::Graphics& g, juce::Button& btn,
                                   const juce::Colour& bgColour,
                                   bool highlight, bool down) override
        {
            const auto r   = btn.getLocalBounds().toFloat().reduced (0.5f);
            const float cr = r.getHeight() * dcui::ChipChrome::kRadiusFactor;

            auto fill = bgColour;
            if (down)      fill = fill.contrasting (0.10f);
            else if (highlight) fill = fill.contrasting (0.05f);

            g.setColour (fill);
            g.fillRoundedRectangle (r, cr);

            g.setColour (btn.findColour (juce::TextButton::textColourOffId)
                            .withMultipliedAlpha (0.20f));
            g.drawRoundedRectangle (r, cr, dcui::ChipChrome::kOutlineWidth);
        }

        void drawButtonText (juce::Graphics& g, juce::TextButton& btn,
                             bool /*isHover*/, bool /*isDown*/) override
        {
            const auto b = btn.getLocalBounds().toFloat().reduced (2.0f, 2.0f);
            if (b.isEmpty()) return;

            // Text-only chip — the dot minimap was dropped at 28 px row height.
            // Font scales with the chip height so it stays legible at smaller
            // row heights without overflowing taller variants.
            g.setColour (btn.findColour (juce::TextButton::textColourOffId));
            g.setFont (DrawnCurveLookAndFeel::makeFont (
                juce::jmin (12.0f, b.getHeight() * 0.55f)));
            g.drawFittedText (btn.getButtonText(), b.toNearestInt(),
                              juce::Justification::centred, 2);
        }
    };

    std::array<SubfamilyLF,      kMaxModes> _subfamilyLF;
    std::array<juce::TextButton, kMaxModes> subfamilyBtns;

    // Transformation / action row buttons
    juce::TextButton scaleNotationBtn;  ///< ♯/♭ toggle — switches chromatic note label style
    juce::TextButton scaleRotateBtn;    ///< ↻  transpose PCS + root up by 1 semitone
    juce::TextButton scaleAllBtn;       ///< ●  all 12 notes active
    juce::TextButton scaleNoneBtn;      ///< ○  root only
    juce::TextButton scaleInvBtn;       ///< ◑  complement (toggle membership)
    juce::TextButton scaleRootBtn;      ///< ◆  enter root-select mode

    // Status labels (mode name + decimal bitmask)
    juce::Label scaleLabel { {}, "Scale" };   ///< Dynamic mode name or "Custom"
    juce::Label maskLabel;                     ///< Decimal bitmask display (read-only)

    ScaleLattice   scaleLattice;
    ChromaticWheel chromaticWheel;

    /// Which scale-picker visualisation(s) are shown in the musical zone.
    /// Pure UI preference — not in APVTS.
    enum ScaleView { ViewRows = 0, ViewWheel = 1, ViewBoth = 2 };
    int              _scaleViewMode { ViewBoth };
    SegmentedControl scaleViewCtrl;

    static constexpr int kScaleLatticeH = 184;

    // Recognition cache — updated by updateScaleStatus(), read by updateScalePresetButtons().
    int _recognisedFamily { -1 };
    int _recognisedMode   { -1 };

    // Active browsed family (tab highlight + chip row) — set by setActiveFamily().
    // kRecentFamilyIdx is a virtual sentinel meaning "show _palettes".
    static constexpr int kRecentFamilyIdx = dcScale::kNumFamilies;   // = 8
    static constexpr int kMaxRecentMasks  = 5;       ///< max palettes shown in the Recent tab
    static constexpr int kMaxPaletteChips = 6;       ///< T2.7: chips in the always-visible strip
    int _activeFamilyIdx   { 0 };
    int _numSubfamilyChips { 0 };

    /// T2.7 (visual-audit-2026-04 §4): a "scale palette" is the bundle of
    /// scale structure + tonal centre that the user thinks of as one unit
    /// when musicking — tapping a palette chip restores both at once.
    /// Persistence lives with the future preset save (§ 6.1); for now the
    /// list is auto-populated from recent picks and lives only in editor
    /// state.
    struct ScalePalette
    {
        uint16_t relMask;   ///< root-relative interval set
        uint8_t  root;      ///< 0..11 (C..B)

        bool operator== (const ScalePalette& o) const noexcept
        {
            return relMask == o.relMask && root == o.root;
        }
    };

    // Recent-history tab: most recently applied palettes, newest first.
    juce::TextButton          recentFamilyBtn;     ///< "Recent" tab (9th in family bar)
    std::vector<ScalePalette> _palettes;           ///< palettes, max kMaxRecentMasks (Recent) / kMaxPaletteChips (strip)

    /// T2.7: the always-visible palette strip (lives in the settings band's
    /// left half). Each chip shows the scale-name + root-letter; tapping
    /// applies both as one gesture so palette-switching mid-musicking is a
    /// single-tap operation.
    std::array<juce::TextButton, kMaxPaletteChips> paletteChips;

    /// "+" button — always in the eyebrow, next to the lane selector.
    /// Adds a lane (up to kMaxLanes). Shown only when capacity allows.
    juce::TextButton eyebrowAddLaneBtn;
    /// "−" button — always in the eyebrow, next to the lane selector.
    /// Removes the focused lane. Shown only when more than one lane is active.
    juce::TextButton eyebrowDeleteLaneBtn;

    // ── Editor state ──────────────────────────────────────────────────────────
    bool _lightMode         { true  };
    bool _useFlats          { false };   ///< Chromatic notation: false = ♯ names, true = ♭ names
    int  _focusedLane       { 0     };   ///< Which lane's shaping / notes are shown
    bool _scaleOverlayOpen  { false };   ///< true while the scale browser overlay is visible

    /// Right rail is permanently removed — layout is always full-width canvas.
    /// Kept as a compile-time constant (false) so old branches compile cleanly
    /// until they are fully pruned.
    static constexpr bool _railExpanded = false;

    /// Last mode index selected per family (index 0..kNumFamilies-1).
    /// Persists across tab switches so re-visiting a family restores the last mode used.
    std::array<int, dcScale::kNumFamilies> _lastModePerFamily {};   // default = 0 (first mode)

    // Panel rects (set in resized, read in paint).
    juce::Rectangle<int> _stagePanel;
    juce::Rectangle<int> _globalPanel;
    juce::Rectangle<int> _focusedLanePanel;
    juce::Rectangle<int> _lanesPanel;
    juce::Rectangle<int> _musicalPanel;
    /// Top-left of first matrix row (used by paint() to draw lane colour dots).
    juce::Point<int>     _matrixRowOrigin;
    int                  _matrixRowStride { 35 };  ///< px per matrix row (matRowH=32 + 3 gap)

    // Legacy aliases still referenced by parameterChanged / updateScaleVisibility.
    juce::Rectangle<int>& _secTransport   = _globalPanel;
    juce::Rectangle<int>& _secShaping     = _focusedLanePanel;
    juce::Rectangle<int>& _secRouting     = _lanesPanel;
    juce::Rectangle<int>  _secNotes;   // kept for note-editor layout in resized()

    bool _showingAllLanes  { false };   ///< true when the "*" (All Lanes) tab is active.
    bool _musicalExpanded  { false };   ///< true when the musical zone is expanded

    juce::TextButton musicalToggleBtn;  ///< collapses / expands the musical zone

#if defined(DC_HAVE_PER_LANE_PLAYBACK_PARAMS)
    /// Rebind speed slider + direction control to lane-specific params (lane ≥ 0)
    /// or to global params (lane < 0, i.e. the "*" tab).
    void bindPlaybackToLane (int lane);
#endif

    // ── Scale browser overlay ─────────────────────────────────────────────────
    /**
     * Full-editor backdrop for the scale browser overlay.
     * Dims everything behind it; scale browser components are reparented INTO this
     * overlay on open (so they paint on top of the dim, like RoutingOverlay's children)
     * and reparented back to DrawnCurveEditor on close.
     * Tapping outside panelRect dismisses it.
     */
    struct ScaleOverlay : public juce::Component
    {
        ScaleOverlay() = default;

        juce::Rectangle<int>  panelRect;
        bool                  _lightMode { true };
        std::function<void()> onDismiss;

        void setLightMode (bool b) { _lightMode = b; repaint(); }

        void paint (juce::Graphics& g) override
        {
            // T2.8: shared overlay chrome — same backdrop + elevated panel
            // treatment as RoutingOverlay + HelpOverlay.  Scale-browser
            // components (children) paint on top of the panel.
            dcui::OverlayChrome::paintBackdrop (g, _lightMode, getLocalBounds());
            dcui::OverlayChrome::paintPanel    (g, _lightMode, panelRect.toFloat());
        }

        void mouseDown (const juce::MouseEvent& e) override
        {
            if (onDismiss && ! panelRect.contains (e.getPosition()))
                onDismiss();
        }

        // Always true: scale browser children handle their own events inside the panel;
        // outside-panel taps fall through to mouseDown() for dismiss.
        bool hitTest (int, int) override { return true; }

        JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (ScaleOverlay)
    };

    ScaleOverlay _scaleOverlay;

    // ── Standalone MIDI output ─────────────────────────────────────────────────
    /// Button shown in the utility bar (standalone only); label = device name or "MIDI Out".
    juce::TextButton midiOutBtn { "MIDI Out" };
    /// Virtual MIDI source port — created once on standalone launch, kept alive so other apps
    /// retain their connection.  Muted/unmuted via _virtualPortMuted (stops sending, not destroyed).
    std::unique_ptr<juce::MidiOutput> _virtualMidiPort;
    bool _virtualPortMuted { false };
    /// Optional direct-target device (user picks from popup; nullptr = virtual port only).
    std::unique_ptr<juce::MidiOutput> _standaloneOut;
    /// Show a PopupMenu of available MIDI output devices.
    void showMidiOutputPicker();
    /// Update button label to reflect current virtual port + direct target state.
    void updateMidiOutBtnText();

    // ── Private helpers ───────────────────────────────────────────────────────
    void setupSlider (juce::Slider& s, juce::Label& l,
                      const juce::String& labelText,
                      juce::Slider::SliderStyle style = juce::Slider::LinearHorizontal);

    void applyTheme();
    void openScaleOverlay();
    void closeScaleOverlay();
    void onSyncToggled    (bool isSync);

    /// Rebind shaping sliders + range slider to the given lane's APVTS params.
    void bindShapingToLane (int lane);

    /// Set _focusedLane, update canvas, rebind shaping, refresh note editor.
    void setFocusedLane (int lane);

    void updateMsgTypeButtons();      // kept for backward compat, delegates to lane row
    void updateLaneRow      (int lane);   ///< Refresh target/detail/channel display for one lane
    void updateAllLaneRows  ();           ///< Refresh all active lane rows

    /// Rebuild laneFocusCtrl segments to match proc.activeLaneCount.
    void updateLaneFocusCtrl();

    /// Increment proc.activeLaneCount (up to kMaxLanes), refresh layout.
    void addLane();
    /// Remove lane 'lane' (shift down), adjust focus, refresh layout.
    void deleteLane (int lane);
    void updateScaleVisibility();
    void setActiveFamily (int familyIdx);     ///< Populate subfamily chips for the chosen family.
    /// T2.7: push (relMask + root) palette to history; refresh Recent tab + chip strip.
    void addRecentPalette (uint16_t relMask, int root);
    /// T2.7: rebuild paletteChips text + visibility from `_palettes`.
    void updatePaletteChips();
    /// T2.7: apply a palette atomically — sets root + mask in one call,
    /// then refreshes UI.
    void applyPalette (const ScalePalette& p);
    /// T2.7: produce the short label shown on a palette chip ("Maj C", "Dor F#", "Pen G").
    juce::String paletteShortLabel (const ScalePalette& p) const;
    void updateScalePresetButtons();          ///< Colour-only refresh (uses cached recognition).
    void updateScaleStatus();                 ///< Full refresh: recognition → cache → labels → colours.
    void updateRangeSlider();
    void updateRangeLabel();
    void applyRangeLabelText (const juce::String& text);
    void updateSpeedLabel();

    /// Refresh both tick-count labels and their step-size annotations.
    void refreshTickLabels();
    /// Step size annotation text for Y axis (semitones in Note mode, else empty).
    juce::String yTickText (int n) const;
    /// Step size annotation text for X axis (seconds in free mode, beats in sync mode).
    juce::String xTickText (int n) const;

    void parameterChanged (const juce::String& paramID, float newValue) override;

    friend class RoutingOverlay;   ///< Needs access to proc, laneTypeBtn, updateLaneRow(), etc.

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (DrawnCurveEditor)
};
